### PR TITLE
installation in vue js added

### PR DESCRIPTION
**Pull request by masumonline**
Vue js 3 and 2 installation information added in the README File.

### CODE REVIEW

**Comment by saadeghi** [comment]
@masumonline Thanks. There's a typo on `Versel`.  
Can you fix that please?

**Comment by masumonline** [comment]
i fixed it.

**Comment by saadeghi** [comment]
Great.

**Comment by shaikhhamza11** [comment]
It doesn't work after refresh in react

**Comment by saadeghi** [comment]
@shaikhhamza11 Please open a new issue and provide a code example so I can reproduce the issue.

**Pull request merged**
